landingpage/urls.py
from django.urls import path
from . import views

app_name = "landingpage"
urlpatterns = [
    path("", views.landingpage, name="landingpage")
]

notes/urls.py
from django.urls import path

from . import views

app_name = "notes"
urlpatterns = [
    path("edit/<str:note_slug>", views.edit, name="edit"),
    path("overview/", views.overview, name="overview"),
    path("note/", views.note, name="note"),
    path("note/<str:note_slug>", views.note, name="note"),
    path("create/", views.create, name="create"),
    path("delete/<str:note_slug>", views.delete, name="delete"),
    path("addcomment/<str:note_slug>", views.add_comment, name="add_comment"),
    path("add_help_request/<str:note_slug>", views.add_help_request, name="add_help_request")
]

opennote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("user/", include("user.urls")),
    path("users/", include("users.urls")),
    path("notes/", include("notes.urls")),
    path("todo/", include("todo.urls")),
    path("study/", include("study.urls")),
    path("", include("landingpage.urls")),
    path('admin/', admin.site.urls),
]

study/urls.py
from django.urls import path
from . import views

app_name = "study"
urlpatterns = [
    path("plan/", views.plan, name="plan"),
    path("createtask/", views.create_task, name="create_task"),
    path("", views.index, name="index")

]

todo/urls.py
from django.urls import path
from . import views


app_name = "todo"
urlpatterns = [
    path("", views.todo, name="todo"),
    path("add/", views.add, name="add")
]

user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("messages/", views.messages, name="messages"),
    path("messageuser/<str:receiver>", views.message_user, name="message_user")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register")
]

landingpage/models.py
from django.db import models

# Create your models here.

landingpage/views.py
from django.shortcuts import render

# Create your views here.

def landingpage(request):

    return render(request, "landingpage/index.html", {
        
    })

landingpage/templates/landingpage/index.html
{% extends "landingpage/layout.html" %}

{% block main %}
    <h1>ACTION</h1>
{% endblock %}

landingpage/templates/landingpage/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Opennote</title>
        <link rel="stylesheet" href="{% static 'landingpage/styles.css' %}">
        {% block head%}
        {% endblock %}
    </head>
    <body>
        <div id="container">
            <header>
                <div>
                    {% if request.user.is_authenticated %}
                        Logged in as: {{request.user|title}}
                    {% endif %}
                </div>
                <div>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'users:logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'users:login' %}">Login</a>
                        /
                        <a href="{% url 'users:register' %}">Register</a>
                    {% endif %}
                </div>
            </header>
            <aside>
                <div>
                    <a href="{% url 'landingpage:landingpage' %}">Main</a>
                </div>
                <div>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'notes:create' %}">Create</a>
                    {% else %}
                        <a href="{% url 'notes:overview'%}">Notes</a>
                    {% endif %}
                </div>
                <div>
                    <a href="{%url 'notes:overview' %}">Overview</a>
                </div>
                <div>
                    <a href="{% url 'user:messages' %}">Inbox</a>
                </div>
                <div>
                    <a href="{% url 'study:plan' %}">Study Plan</a>
                </div>
            </aside>
            <main>
                {% block main %}
                
                {% endblock %}
            </main>
            <footer></footer>
        </div>
        {% block body %}        
        {% endblock %}
    </body>
</html>