opennote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("user/", include("user.urls")),
    path("users/", include("users.urls")),
    path("notes/", include("notes.urls")),
    path("todo/", include("todo.urls")),
    path("study/", include("study.urls")),
    path("", include("landingpage.urls")),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path
from . import views


app_name = "todo"
urlpatterns = [
    path("", views.todo, name="todo"),
    path("add/", views.add, name="add")
]

todo/models.py
from django.db import models

# Create your models here.

todo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django import forms
from django.urls import reverse

# Create your views here.

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")


def todo(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []

    return render(request, "todo/index.html", {
        "tasks": request.session["tasks"]
    })


def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            print(request.session["tasks"])
            return HttpResponseRedirect(reverse("todo:todo"))
        else:
            return render(request, "todo/add.html", {
                "form": form
            })
        
    return render(request, "todo/add.html", {
        "form": NewTaskForm()
    })

todo/templates/todo/add.html
{% extends "landingpage/layout.html" %}

{% block main %}
    <h1>Add task</h1>


    <form action="{% url 'todo:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}
                
            

todo/templates/todo/index.html
{% extends "landingpage/layout.html" %}

{% block main %}
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'todo:add' %}">Add task</a>
{% endblock %}