notes/urls.py
from django.urls import path

from . import views

app_name = "notes"
urlpatterns = [
    path("edit/<str:note_slug>", views.edit, name="edit"),
    path("overview/", views.overview, name="overview"),
    path("note/", views.note, name="note"),
    path("note/<str:note_slug>", views.note, name="note"),
    path("create/", views.create, name="create"),
    path("delete/<str:note_slug>", views.delete, name="delete"),
    path("addcomment/<str:note_slug>", views.add_comment, name="add_comment"),
    path("add_help_request/<str:note_slug>", views.add_help_request, name="add_help_request")
]

opennote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("user/", include("user.urls")),
    path("users/", include("users.urls")),
    path("notes/", include("notes.urls")),
    path("todo/", include("todo.urls")),
    path("study/", include("study.urls")),
    path("", include("landingpage.urls")),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path
from . import views


app_name = "todo"
urlpatterns = [
    path("", views.todo, name="todo"),
    path("add/", views.add, name="add")
]

user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("messages/", views.messages, name="messages"),
    path("messageuser/<str:receiver>", views.message_user, name="message_user")
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import random
import string

# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f"{self.name}"

class Note(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes")
    title = models.CharField(max_length=64, blank=True)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, related_name="notes")
    note = models.TextField()
    creation_time = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    

    def __str__(self):
        return f"{self.title}, {self.category}"
    
    def save(self, *args, **kwargs):
        if not self.id:
            if not self.slug:
                category_slug = slugify(self.category)
                title_words = [word for word in self.title.split() if word.lower() not in ['and', 'the', 'of']]
                title_slug = slugify(' '.join(title_words))
                random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
                self.slug = f"{category_slug}-{title_slug}-{random_string}"
            else:
                saved_note = Note.objects.get(id=self.id)
                self.slug = saved_note.slug
                self.title = saved_note.title


        super(Note, self).save(*args, **kwargs)
    
class Comment(models.Model):
    comment = models.CharField(max_length=512)
    note = models.ForeignKey(Note, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    creation_time = models.DateTimeField(auto_now_add=True)

class HelpRequests(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="helpRequests")
    note = models.OneToOneField(Note, on_delete=models.CASCADE, related_name="helpRequests")
    offer = models.CharField(max_length=10, blank=True)
    description = models.CharField(max_length=256, blank=True)

notes/forms.py
from django import forms

class NoteForm(forms.Form):
    title = forms.CharField(max_length=32)
    category = forms.CharField(
        max_length=32,
        label="Category:",
        widget=forms.TextInput(attrs={'list': 'categories', "spellcheck": "false"})
        )
    note = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 16}),
    )

class OverviewFilter(forms.Form):
    author = forms.CharField(max_length=32, required=False)
    category = forms.CharField(max_length=64, required=False)
    search = forms.CharField(max_length=64, required=False)
    TIME_PERIOD_CHOICES = [
        ('all', 'All'),
        ('1_month', '1 Month'),
        ('3_months', '3 Months'),
        ('1_year', '1 Year'),
    ]
    time_period = forms.ChoiceField(choices=TIME_PERIOD_CHOICES, required=False, initial='all')

class CommentForm(forms.Form):
    comment = forms.CharField(
        max_length=512,
        widget=forms.Textarea(attrs={"rows": 3})
    )

class HelpDescriptionForm(forms.Form):
    description = forms.CharField(
        max_length=256,
        widget=forms.Textarea(attrs={"rows": 3}),
        required=False

    )
    offer = forms.ChoiceField(
        choices=[("Help", "Help"), ("None", "None")],
        widget=forms.RadioSelect,
        required=False
    )

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NoteForm, OverviewFilter, CommentForm, HelpDescriptionForm
from .models import Categories, Note, Comment, HelpRequests
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import F

from notes.view_ex.get_note import get_note
from notes.view_ex.filter_overview import filter_overview

# Create your views here.


@login_required
def create(request):
    if request.method == "POST":
        # First we do category, check if it is in database, else we save it. save id for later
        note = save_note(request)

        return redirect("notes:edit", note.slug)
    else:
        form = NoteForm()

    return render(request, "notes/create.html", {
        "form": form,
        "categories": Categories.objects.all()

    })
# Need to have some sort of filter here, need based on author. category, words
def overview(request):
    if request.method == "POST":

        note_list = filter_overview(request)
        overviewFilter = OverviewFilter(request.POST)

    else:
        note_list = Note.objects.all()[:30]
        overviewFilter = OverviewFilter

    return render(request, "notes/overview.html", {
        "notes": note_list,
        "overviewFilter": overviewFilter
    })

def note(request, note_slug=None):
    if note_slug is None:
        return redirect("notes:overview")
    else:
        # We get object
        try:
            noteObject = Note.objects.get(slug=note_slug)
            comments = Comment.objects.filter(note=noteObject)

            if noteObject.author == request.user:
                return redirect("notes:edit", note_slug)
            noteObject.views = F('views') + 1
            noteObject.save()
            noteObject = get_note(note_slug)

        except ObjectDoesNotExist:
            return redirect("notes:overview")
        
    try:
        help_request = HelpRequests.objects.get(note=get_note(note_slug))
        help_description_form = HelpDescriptionForm(
            initial={"description": help_request.description, "offer": help_request.offer})

        help_description_form.fields["description"].widget.attrs["disabled"] = "disabled"
        help_description_form.fields["offer"].widget.attrs["disabled"] = "disabled"
        


    except ObjectDoesNotExist:
        help_description_form = None   

    return render(request, "notes/note.html", {
        "title": noteObject.title,
        "category": noteObject.category,
        "note": noteObject.note,
        "author": noteObject.author,
        "views": noteObject.views,
        "note_slug": note_slug,
        "commentForm": CommentForm,
        "comments": comments,
        "helpDescriptionForm": help_description_form
    })

def edit(request, note_slug):

    # Need to make this in case of linking to edit page i guess
    if not request.user.is_authenticated:
        return redirect("notes:note", note_slug)
    else:
        # In edit, we may first get the note fra database

        if request.method == "POST":
            # can i do something like this
            noteObject = get_note(note_slug)

            if noteObject.author == request.user:

                noteObject.note = request.POST["note"]
                noteObject.save()
                form = NoteForm({
                        'title': noteObject.title,
                        'category': noteObject.category,
                        'note': noteObject.note
                    })
            else:
                return redirect("notes:note", note_slug)

        else:
            try:
                noteObject = Note.objects.get(slug=note_slug)
                #need to fix this. Thats next
                form = NoteForm({
                    'title': noteObject.title,
                    'category': noteObject.category,
                    'note': noteObject.note
                })
            except ObjectDoesNotExist:
                #Should i maybe throw an error here to inform user page does not exist?
                return redirect("notes:overview")
    

    # Getting help request
    
    try:
        help_request = HelpRequests.objects.get(note=get_note(note_slug))
        help_description_form = HelpDescriptionForm(
            initial={"description": help_request.description, "offer": help_request.offer})
    except ObjectDoesNotExist:
        help_description_form = HelpDescriptionForm()
        
    return render(request, "notes/edit.html", {
        "form": form,
        "title": noteObject.title,
        "category": noteObject.category,
        "note_slug": note_slug,
        "comments": Comment.objects.filter(note=noteObject),
        "commentForm": CommentForm,
        "helpDescriptionForm": help_description_form,
        "views": noteObject.views

    })

@login_required
def delete(request, note_slug):
    note = get_object_or_404(Note, slug=note_slug)
    
    if note.author != request.user:
        return redirect("landingpage:landingpage")

    if request.method == "POST":
        note.delete()
        return redirect("notes:overview")
    
    return redirect("notes:edit", note_slug)

def save_note(request, note_slug=None):
    form = NoteForm(request.POST)
    if form.is_valid():

            category_name = form.cleaned_data["category"]
            category, created = Categories.objects.get_or_create(name=category_name)

            if note_slug is None:
                note = Note(
                    title=form.cleaned_data["title"],
                    category=category,
                    note=form.cleaned_data["note"],
                    author=request.user
                )

            else:
                note = Note.objects.get(slug=note_slug)
                note.note = form.cleaned_data["note"]

            note.save()
            return note

@login_required    
def add_comment(request, note_slug):
    # We need to create a form field, textarea i guess. make it petite, place it under.
    # Maybe its time to bring out the javascript 
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data["comment"]
            note = get_note(note_slug)

            new_comment = Comment(
                comment=comment,
                note=note,
                author=request.user
            )
            new_comment.save()
            
    return redirect("notes:note", note_slug=note_slug)

@login_required
def add_help_request(request, note_slug):
    if request.method == "POST":
        form = HelpDescriptionForm(request.POST)
        if form.is_valid():

            # first see if help request exists? then just add to it. 

            try:
                help_request = HelpRequests.objects.get(note=get_note(note_slug))
            except HelpRequests.DoesNotExist:
                
                help_request = HelpRequests.objects.create(
                    author=request.user,
                    note=Note.objects.get(slug=note_slug),
                    offer=form.cleaned_data["offer"],
                    description=form.cleaned_data["description"]
                )

            else:
                help_request.offer = form.cleaned_data["offer"]
                help_request.description = form.cleaned_data["description"]
                help_request.save()

    return redirect("notes:edit", note_slug=note_slug)
# What does this function need to do. About the same as add comment i guess
#   

notes/templates/notes/create.html
{% extends "landingpage/layout.html" %}

{% block main %}
    <div class="noteMain">
        <div class="noteForm">
            <form action="{% url 'notes:create' %}" method="post">
                {% csrf_token %}
                <div class="noteHeader">
                    <div>
                        {{form.title.label_tag}}
                        {{form.title}}
                        {{form.category.label_tag}}
                        {{form.category}}
                    </div>
                </div>
                <datalist id="categories">
                    {% for category in categories %}
                        <option value="{{category.name}}">
                    {% endfor %}
                </datalist>
                <div class="noteTextField">
                    {{form.note}}
                </div>
                <div class="noteFooter">
                    <div></div>
                    <input type="submit" value="Save">
                </div>
            </form>
        </div>
    </div>
        
{% endblock %}

notes/templates/notes/edit.html
{% extends "landingpage/layout.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'notes/styles.css' %}">
{% endblock %}

{% block main %}
    <div class="noteMain">
        <div class="noteForm">
            <form id="edit-form" action="{% url 'notes:edit' note_slug=note_slug %}" method="post">
                {% csrf_token %}
                <div class="noteHeader">
                    <div>
                        {{title}}
                    </div>
                    <div>
                        Category:
                        {{category}}
                    </div>
                </div>
                <datalist id="categories">
                    {% for category in categories %}
                        <option value="{{category.name}}">
                    {% endfor %}
                </datalist>
                <div class="noteTextField">
                    {{form.note}}
                </div>
            </form>
            <div class="noteFooter">
                <div>
                    Views: {{views}}
                </div>
                <div class="footerButtons">
                    <input type="button" value="Ask for help" onclick="hello()">
                    <input  type="button" 
                            value="Delete" 
                            id="deleteButton"
                            onclick="document.getElementById('id_delete_note_modal').style.display='block'">
                    </input>
                    <input form="edit-form" type="submit" value="Save">
                </div>   
            </div>
        </div>
        <div class="comment-area" id="comment-area">
            <h2>
                Comments
            </h2>
            <div class="comments">
                {% for comment in comments %}
                <div class="comment">{{comment.author|title}}: {{comment.comment}}</div>
                {% endfor %}   
            </div>
        </div>
        <div class="comment-form">
            <form action="{% url 'notes:add_comment' note_slug=note_slug%}" method="post">
                {% csrf_token %}
                {{ commentForm.comment}}
                <input type="submit" value="Add comment" class="comment-button">
            </form>
        </div>
        <div class="help-section" id="help-section">
            <form action="{% url 'notes:add_help_request' note_slug=note_slug %}" method="post" class="help-section-form">
                {% csrf_token %}
                <div>
                    <p>I need help with: </p>
                    {{helpDescriptionForm.description}}
                </div>
                <div>
                    <p>Offer: </p>
                    {{helpDescriptionForm.offer}}
                </div>
                <div>
                    <input type="submit" value="Flagg for help" class="help-button">
                </div>
            </form>
        </div>
    </div>

    <div id="id_delete_note_modal" class="modal">
        <form class="modal-content" method="post" action="{% url 'notes:delete' note_slug=note_slug %}">
            {% csrf_token %}
            <div class="modal-container">
                <h2>Sure you want to delete post?</h2>
                <div class="modal-buttons">
                    <input type="button" value="Cancel" class="modal-button-cancel modal-button" onclick="document.getElementById('id_delete_note_modal').style.display='none'">
                    <input type="submit" value="Delete" class="modal-button-delete modal-button">
                </div>
            </div>
        </form>
    </div>

    <script>
            helpSection = document.getElementById("help-section")
            helpSection.style.display = "none"
        function hello() {
            
            if (helpSection.style.display == "none") {
                helpSection.style.display = "flex"
            } else {
                helpSection.style.display = "none"
            }
        }

        // Get the modal
        var modal = document.getElementById('id_delete_note_modal');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
        }
    </script>
{% endblock %}

notes/templates/notes/note.html
{% extends "landingpage/layout.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'notes/styles.css' %}">
{% endblock %}

{% block main %}
    <div class="noteMain">
        <div class="noteForm">
            <form>
                <div class="noteHeader">
                    <div>
                        {{title}}
                    </div>
                    <div>
                        Category:
                        {{category}}
                    </div>
                </div>
                <div class="noteTextField">
                    <textarea rows="16" disabled="true">{{note}}</textarea>
                </div>
            </form>
            <div class="noteFooter">
                <div>
                    Views: {{views}}
                </div>
                <div>
                    <a id="id_user_select_button">{{author|title}}</a>
                </div>
            </div>
        </div>
        <div class="comment-area" id="comment-area">
            <h2>
                Comments
            </h2>
            <div class="comments">
                {% for comment in comments %}
                <div class="comment">{{comment.author|title}}: {{comment.comment}}</div>
                {% endfor %}   
            </div>
        </div>
        <div class="comment-form">
            <form action="{% url 'notes:add_comment' note_slug=note_slug%}" method="post">
                {% csrf_token %}
                {{ commentForm.comment}}
                <input type="submit" value="Add comment" class="comment-button">
            </form>
        </div>
        {% if helpDescriptionForm %}
            <div class="help-section" id="help-section" style="display: flex;">
                <form action="" class="help-section-form" disabled>
                    <div>
                        <p>I need help with: </p>
                        {{helpDescriptionForm.description}}
                    </div>
                    <div>
                        <p>Offer: </p>
                        {{helpDescriptionForm.offer}}
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
    {% include 'notes/user_modal.html' %}
{% endblock %}

{% block body %}
    <script src="{% static 'notes/js/functionality.js' %}"></script>
{% endblock%}

notes/templates/notes/overview.html
{% extends "landingpage/layout.html" %}

{% block main %}
<div class="overviewMain">
    <form action="{% url 'notes:overview' %}" method="post">
        {% csrf_token %}
        <div class="noteHeader">
            <div>
                {{overviewFilter.author.label_tag}}
                {{overviewFilter.author}}
            </div>
            <div>
                {{overviewFilter.category.label_tag}}
                {{overviewFilter.category}}
            </div>
            <div>
                {{ overviewFilter.search.label_tag}}
                {{ overviewFilter.search }}
            </div>
            <input type="submit" value="Search" class="overviewButton">
        </div>
    </form>
    <ul class="overviewList">
        {% for note in notes %}
        <a href="{% url 'notes:note' note.slug %}" class="overviewNote">
            <div>
                {{note.title}}
            <div class="overviewNoteCredentials">
                {{note.creation_time}} by {{note.author|title}}

            </div>
            </div>
        
           
        </a>
        {% endfor %}
    </ul>
</div>
    
    
{% endblock %}

notes/templates/notes/user_modal.html
<div id="id_select_user_modal" class="modal">
    <div class="modal-content">
        <div class="modal-container">
            <div class="modal-user-info">
                <div class="modal-user-info-block">
                    <h2>{{author|title}}</h2>
                    <p>Joined: 2023</p>
                    <p>P: 3000</p>
                </div>
                <div class="modal-user-info-block">
                    <h3>About:</h3>
                    <p>Write a bit about yourself, what are you learning, and stuff!</p>
                </div>
            </div>
            <div class="modal-user-interaction">
                <div class="modal-buttons">
                    <a href="{% url 'user:message_user' receiver=author %}" class="modal-button">Message</a>
                    <input type="button" value="Follow" class="modal-button modal-button-mid">
                    <input type="button" value="View profile" class="modal-button">
                </div>
            </div>
        </div>
    </div>
</div>