opennote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("user/", include("user.urls")),
    path("users/", include("users.urls")),
    path("notes/", include("notes.urls")),
    path("todo/", include("todo.urls")),
    path("study/", include("study.urls")),
    path("", include("landingpage.urls")),
    path('admin/', admin.site.urls),
]

study/urls.py
from django.urls import path
from . import views

app_name = "study"
urlpatterns = [
    path("plan/", views.plan, name="plan"),
    path("createtask/", views.create_task, name="create_task"),
    path("", views.index, name="index")

]

todo/urls.py
from django.urls import path
from . import views


app_name = "todo"
urlpatterns = [
    path("", views.todo, name="todo"),
    path("add/", views.add, name="add")
]

study/models.py
from django.db import models

# Create your models here.

study/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
def plan(request):
    name = "Billy"

    return render(request, "study/plan.html", {
        "name": name
    })

@login_required
def create_task(request):
    if request.method == "POST":
        print("Hello")

def index(request):
    context = {
        "bruker": "Martin",
        "poeng": 23       
               }
    return render(request, "study/index.html", context)

study/templates/study/index.html
{% extends "landingpage/layout.html" %}

<!--Vi drøyer litt med load static her, da jeg ikke har helt kontroll på det-->
{% block main %}

<p>HELLO, Welcome to my fantastic boat!</p>
<p>{{ bruker }}</p>

{% endblock%}

<!-- Vrient med comments da. Ser pent ut da,
 
    Kan gå over flere linjer og, det er bra.

    La oss planlegge litt her. 
    Alt er pakket inn i en layout egentlig. 
    1. må importere eller extende landingpage/layout. 
    2. Så bygges ting inne i block main. Denne er laget i layouten tror jeg
        Layouten tar seg av det rundt og som er felles for alle sidene. 
        Så lager jeg ny css for main. er ikke det lurt da?

    3. Er så klar til å bygge der inne. trenger vel en form for grid?
        - bygges med klosser. burde jeg tegne en skisse?
        - Må hvertfall kjøre lett. Ikke noe fance nå trur jeg
        - Må bli mere i morgen du. 

    4. Skal vi se litt på databaser. Begynne smått med det.



er vel det som er årsak-->

study/templates/study/plan.html
{% extends "landingpage/layout.html" %}

{% load static %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'study/studyStyles.css' %}">
{% endblock %}

{% block main %}
    <div class="studyPlanMain" id="studyPlanMain">
        <div class="planed-area planing-box" id="planed-area">

        </div>
        <div class="repeat-area planing-box" id="repeat-area"></div>
        <div class="done-area planing-box" id="done-area"></div>
        <div class="button-area" id="button-area">
            <form action="{% url 'study:create_task' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Create Task">
            </form>
        </div>
    </div>

{% endblock %}